name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup environment
      run: |
          ./setup.sh
    - name: Build
      run: |
          source ./emsdk/emsdk_env.sh
          cd cpp/1_simple_function_call
          ./build.sh
