name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup environment
      run: |
          ./setup.sh
    - name: Build
      run: |
          source ./emsdk/emsdk_env.sh
          cd cpp/1_simple_function_call
          ./build.sh
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./cpp/1_simple_function_call/target
